### PR TITLE
added communities served to model and tables

### PR DESCRIPTION
**Pull request by RobertMisch**
## Description ##

Clearly documents the reason for the pull request and what has changed. Delete this test and add your own.
- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [x] Have you added two reviewers to this pull request?
- [x] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Comment by xavierhoskins** [comment]
lgtm

**Review by CodyFlys — APPROVED** [review]
Looks good, Will get this tested

**Review by xavierhoskins — APPROVED** [review]
lgtm

**Comment by jessicagertig** [comment]
[build database table structure and relationships](https://trello.com/c/vCUHmpdZ/10-build-database-table-structure-and-relationships)

**Pull request merged**
