### PR TITLE
Feature/bridges table/end point

### PR DESCRIPTION
**Pull request by CodyFlys**
## Description ##

Clearly documents the reason for the pull request and what has changed. Delete this test and add your own.
- [ ] This is a bugfix.
- [x] This is a new feature.
- [x] This is part of a feature.

## Organization ##

- [x] Have you linked this pull request to a Trello card?

## Review ##

- [x] Have you added two reviewers to this pull request?
- [x] Is this a work in process?
- [x] Is this ready to be reviewed?

### CODE REVIEW

**Review by jessicagertig — COMMENTED** [review]
Lets go ahead and remove the readme file from this pull request.  Or rather in future.

**Review by RobertMisch — DISMISSED** [review]
Good work, next we'll have to get on adding the communities served. I noticed that the node packages are in, isn't that supposed to be on the git ignore?

**Review by jessicagertig — APPROVED** [review]

**Comment by jessicagertig** [comment]
Deleted package-lock.json.  Robert Misch also reviewed. Will change settings on reviews so that 'stale' reviews not removed in future.

**Comment by jessicagertig** [comment]
[build database table structure and relationships](https://trello.com/c/vCUHmpdZ/10-build-database-table-structure-and-relationships)

**Pull request merged**
